apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: docrecords
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: docrecords_dockercompose-api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: root
            - name: DB_NAME
              value: docrecords
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: docrecords
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: api-gateway

