apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-control-service
  namespace: docrecords
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-control-service
  template:
    metadata:
      labels:
        app: profile-control-service
    spec:
      containers:
        - name: profile-control-service
          image: docrecords_dockercompose-profile-control-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5008
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: root
            - name: DB_NAME
              value: docrecords
---
apiVersion: v1
kind: Service
metadata:
  name: profile-control-service
  namespace: docrecords
spec:
  ports:
    - port: 5008
      targetPort: 5008
  selector:
    app: profile-control-service

