apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: docrecords
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30001       # Access frontend at http://<host-ip>:30001
  type: NodePort
