apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc               # Name used in the MySQL Deployment to claim this storage
  namespace: docrecords
spec:
  storageClassName: manual      # Must match the PV's storageClassName
  accessModes:
    - ReadWriteOnce             # Must match the PV's accessModes
  resources:
    requests:
      storage: 2Gi              # How much storage we need (must be <= PV's capacity)
