apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local                  # A label — we use this to match with the PVC below
spec:
  storageClassName: manual       # A custom class name — must match between PV and PVC
  capacity:
    storage: 2Gi                 # Reserve 2 gigabytes of disk space
  accessModes:
    - ReadWriteOnce              # Can be mounted by ONE node at a time (correct for a DB)
  hostPath:
    path: "/mnt/data/docrecords-mysql"  # Actual folder on the host Linux machine where data is stored
